# Site settings
baseurl = "https://oveddan.github.io/blog/"
publishDir = "docs"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "en"
title = "Dan Oved's blog"
theme = "cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-106896744-1"
hasCJKLanguage = true

[params]
	name = "Dan Oved's Blog"
	description = "Adventures through the virtual and physical world @ ITP"
	bio = "Adventures through the virtual and physical world @ ITP"
	# Enter optionally your twitter account
	enableRSS = false

	enableGithubIssuesTips = false

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Add custom assets with their paths relative to the static folder
	customCSS = ["/css/style-custom.css"]
	customJS  = []

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	tags = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "I am so the best around."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = ""


# Add additional social link entries underneath
[social]
	#facebook-square = "https://www.facebook.com/DanOved"
  instagram-square = "https://www.instagram.com/stangogh/"
  #twitter-square = "your_twitter_link"
  github-square = "https://github.com/oveddan"
