[build]
  publish = "docs"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.131.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

# Redirect /blog/* to /itp-blog/*
[[redirects]]
  from = "/blog/*"
  to = "/itp-blog/:splat"
  status = 301

[[redirects]]
  from = "/blog"
  to = "/itp-blog/"
  status = 301
