[build]
  publish = "docs"
  command = "hugo && echo '/blog/* /itp-blog/:splat 301' > docs/_redirects && echo '/blog /itp-blog/ 301' >> docs/_redirects"

[build.environment]
  HUGO_VERSION = "0.131.0"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"
